require 'rails_helper'

RSpec.describe 'the landing page' do 
    before :each do 
        visit '/'

        user = User.create!(email: 'test@test.com', password: "test", password_confirmation: "test")

        password = "test"
        @email = 'test@test.com'

        fill_in :email, with: @email
        fill_in :password, with: password

        click_on "Login"
    end 

    it 'should be a page with several options and lets you select a track' do
        expect(page).to have_content("Welcome, #{@email}!")
        expect(current_path).to eq("/profile")

        select("SOF Land Contract", from: "track")  

        click_button("Select Track")
        
        expect(page).to have_content("SOF Land Contract Assessments")
    end 

     it 'should be a page with several options and lets you select a track' do
        select("SOF Land Contract", from: "track")  
        click_button("Select Track")
        
        expect(page).to have_content("SOF Land Contract Assessments")

        fill_in("ruck_hours", with:2)
        fill_in("ruck_minutes", with:15)
        fill_in("five_mile_minutes", with:40)
        fill_in("five_mile_seconds", with:15)
        fill_in("one_and_half_mile_run_minutes", with:10)
        fill_in("one_and_half_mile_run_seconds", with:50)
        fill_in("four_hundred_run_minutes", with:1)
        fill_in("four_hundred_run_seconds", with:30)
        fill_in("pushup_reps", with:50)
        fill_in("pullup_reps", with:12)
        fill_in("hang_minutes", with:1)
        fill_in("hang_seconds", with:19)
        choose(id="units_imperial")
        fill_in("body_weight", with:195)
        select("Back Squat", from: "squat")
        fill_in("squat_weight", with:395) 
        select("Trap Bar", from: "deadlift")
        fill_in("deadlift_weight", with:475)  
        select("Bench Press", from: "press")
        fill_in("press_weight", with:275)
        fill_in("pullup_weight", with:265)
        click_button("Submit Results")

        expect(current_path).to eq("/results")
        expect(page).to have_content("SOF Land Contract Assessment Results")
    end 

     it 'should be a page with several options and lets you select sof maritime contract track' do
        select("SOF Maritime Contract", from: "track")  
        click_button("Select Track")
        
        expect(page).to have_content("SOF Maritime Contract Assessments")

        fill_in("ruck_hours", with:2)
        fill_in("ruck_minutes", with:15)
        fill_in("five_mile_minutes", with:40)
        fill_in("five_mile_seconds", with:15)
        fill_in("two_thousand_swim_minutes", with:40)
        fill_in("two_thousand_swim_seconds", with:15)
        fill_in("one_and_half_mile_run_minutes", with:10)
        fill_in("one_and_half_mile_run_seconds", with:50)
        fill_in("five_hundred_swim_minutes", with:11)
        fill_in("five_hundred_swim_seconds", with:50)
        fill_in("four_hundred_run_minutes", with:1)
        fill_in("four_hundred_run_seconds", with:30)
        fill_in("pushup_reps", with:50)
        fill_in("pullup_reps", with:12)
        fill_in("hang_minutes", with:1)
        fill_in("hang_seconds", with:19)
        choose(id="units_imperial")
        fill_in("body_weight", with:195)
        select("Back Squat", from: "squat")
        fill_in("squat_weight", with:395) 
        select("Trap Bar", from: "deadlift")
        fill_in("deadlift_weight", with:475)  
        select("Bench Press", from: "press")
        fill_in("press_weight", with:275)
        fill_in("pullup_weight", with:265)
        click_button("Submit Results")

        expect(current_path).to eq("/results")
        expect(page).to have_content("SOF Maritime Contract Assessment Results")
    end 

    it 'should be a page with several options and lets you select sof maritime contract track with front squat, straigh bar dl, and oh press' do
        select("SOF Maritime Contract", from: "track")  
        click_button("Select Track")
        
        expect(page).to have_content("SOF Maritime Contract Assessments")

        fill_in("ruck_hours", with:2)
        fill_in("ruck_minutes", with:15)
        fill_in("five_mile_minutes", with:40)
        fill_in("five_mile_seconds", with:15)
        fill_in("two_thousand_swim_minutes", with:40)
        fill_in("two_thousand_swim_seconds", with:15)
        fill_in("one_and_half_mile_run_minutes", with:10)
        fill_in("one_and_half_mile_run_seconds", with:50)
        fill_in("five_hundred_swim_minutes", with:11)
        fill_in("five_hundred_swim_seconds", with:50)
        fill_in("four_hundred_run_minutes", with:1)
        fill_in("four_hundred_run_seconds", with:30)
        fill_in("pushup_reps", with:50)
        fill_in("pullup_reps", with:12)
        fill_in("hang_minutes", with:1)
        fill_in("hang_seconds", with:19)
        choose(id="units_imperial")
        fill_in("body_weight", with:195)
        select("Front Squat", from: "squat")
        fill_in("squat_weight", with:276) 
        select("Straight Bar", from: "deadlift")
        fill_in("deadlift_weight", with:338)  
        select("Overhead Press (1 Arm)", from: "press")
        fill_in("press_weight", with:76)
        fill_in("pullup_weight", with:265)
        click_button("Submit Results")

        expect(current_path).to eq("/results")
        expect(page).to have_content("SOF Maritime Contract Assessment Results")
    end 

    it 'should be a page with several options and lets you select sof land prep track' do
        select("SOF Land Prep", from: "track")  
        click_button("Select Track")
        
        expect(page).to have_content("SOF Land Prep Assessments")
        select("3 Mile Run", from: "prep_run_or_ruck")
        fill_in("ruck_or_run_hours", with:0)
        fill_in("ruck_or_run_minutes", with:30)
        fill_in("one_and_half_mile_run_minutes", with:12)
        fill_in("one_and_half_mile_run_seconds", with:50)
        fill_in("four_hundred_run_minutes", with:1)
        fill_in("four_hundred_run_seconds", with:30)
        fill_in("pushup_reps", with:50)
        fill_in("pullup_reps", with:9)
        fill_in("hang_minutes", with:1)
        fill_in("hang_seconds", with:19)
        choose(id="units_imperial")
        fill_in("body_weight", with:195)
        select("Back Squat", from: "squat")
        fill_in("squat_weight", with:266) 
        select("Trap Bar", from: "deadlift")
        fill_in("deadlift_weight", with:303)  
        select("Bench Press", from: "press")
        fill_in("press_weight", with:194)
        fill_in("pullup_weight", with:215)
        click_button("Submit Results")

        expect(current_path).to eq("/results")
        expect(page).to have_content("SOF Land Prep Assessment Results")
    end 

    it 'should be a page with several options and lets you select sof maritime prep track' do
        select("SOF Maritime Prep", from: "track")  
        click_button("Select Track")
        
        expect(page).to have_content("SOF Maritime Prep Assessments")
        select("3 Mile Run", from: "prep_run_or_ruck")
        fill_in("ruck_or_run_hours", with:0)
        fill_in("ruck_or_run_minutes", with:30)
        fill_in("one_and_half_mile_run_minutes", with:12)
        fill_in("one_and_half_mile_run_seconds", with:50)
        fill_in("five_hundred_swim_minutes", with:11)
        fill_in("five_hundred_swim_seconds", with:50)
        fill_in("four_hundred_run_minutes", with:1)
        fill_in("four_hundred_run_seconds", with:30)
        fill_in("pushup_reps", with:50)
        fill_in("pullup_reps", with:9)
        fill_in("hang_minutes", with:1)
        fill_in("hang_seconds", with:19)
        choose(id="units_imperial")
        fill_in("body_weight", with:195)
        select("Back Squat", from: "squat")
        fill_in("squat_weight", with:266) 
        select("Trap Bar", from: "deadlift")
        fill_in("deadlift_weight", with:303)  
        select("Bench Press", from: "press")
        fill_in("press_weight", with:194)
        fill_in("pullup_weight", with:215)
        click_button("Submit Results")

        expect(current_path).to eq("/results")
        expect(page).to have_content("SOF Maritime Prep Assessment Results")
    end 

    it 'should be a page with several options and lets you select sof maritime prep track' do
        select("SOF Maritime Prep", from: "track")  
        click_button("Select Track")
        
        expect(page).to have_content("SOF Maritime Prep Assessments")
        select("3 Mile Run", from: "prep_run_or_ruck")
        fill_in("ruck_or_run_hours", with:0)
        fill_in("ruck_or_run_minutes", with:30)
        fill_in("one_and_half_mile_run_minutes", with:12)
        fill_in("one_and_half_mile_run_seconds", with:50)
        fill_in("five_hundred_swim_minutes", with:11)
        fill_in("five_hundred_swim_seconds", with:50)
        fill_in("four_hundred_run_minutes", with:1)
        fill_in("four_hundred_run_seconds", with:30)
        fill_in("pushup_reps", with:50)
        fill_in("pullup_reps", with:9)
        fill_in("hang_minutes", with:1)
        fill_in("hang_seconds", with:19)
        choose(id="units_imperial")
        fill_in("body_weight", with:195)
        select("Back Squat", from: "squat")
        fill_in("squat_weight", with:266) 
        select("Trap Bar", from: "deadlift")
        fill_in("deadlift_weight", with:303)  
        select("Bench Press", from: "press")
        fill_in("press_weight", with:194)
        fill_in("pullup_weight", with:215)
        click_button("Submit Results")

        expect(current_path).to eq("/results")
        expect(page).to have_content("SOF Maritime Prep Assessment Results")
    end

    it 'will not have a score less than zero' do
        select("SOF Maritime Prep", from: "track")  
        click_button("Select Track")
        
        expect(page).to have_content("SOF Maritime Prep Assessments")
        select("3 Mile Run", from: "prep_run_or_ruck")
        fill_in("ruck_or_run_hours", with:1)
        fill_in("ruck_or_run_minutes", with:20)
        fill_in("one_and_half_mile_run_minutes", with:20)
        fill_in("one_and_half_mile_run_seconds", with:50)
        fill_in("five_hundred_swim_minutes", with:20)
        fill_in("five_hundred_swim_seconds", with:50)
        fill_in("four_hundred_run_minutes", with:2)
        fill_in("four_hundred_run_seconds", with:30)
        fill_in("pushup_reps", with:20)
        fill_in("pullup_reps", with:3)
        fill_in("hang_minutes", with:0)
        fill_in("hang_seconds", with:19)
        choose(id="units_imperial")
        fill_in("body_weight", with:200)
        select("Back Squat", from: "squat")
        fill_in("squat_weight", with:106) 
        select("Trap Bar", from: "deadlift")
        fill_in("deadlift_weight", with:163)  
        select("Bench Press", from: "press")
        fill_in("press_weight", with:114)
        fill_in("pullup_weight", with:167)
        click_button("Submit Results")

        expect(current_path).to eq("/results")
        
        expect(page).to have_content("SOF Maritime Prep Assessment Results")
        expect(page).to have_content("Overall Score: 5")
        expect(page).to have_content("Strength Score: 13")
        expect(page).to have_content("Conditioning Score: 2")
        expect(page).to have_content("Work Capacity Score: 0")
    end

    it 'will not have scores below zero - sof land prep' do
        select("SOF Land Prep", from: "track")  
        click_button("Select Track")
        
        expect(page).to have_content("SOF Land Prep Assessments")
        select("3 Mile Run", from: "prep_run_or_ruck")
        fill_in("ruck_or_run_hours", with:1)
        fill_in("ruck_or_run_minutes", with:10)
        fill_in("one_and_half_mile_run_minutes", with:44)
        fill_in("one_and_half_mile_run_seconds", with:50)
        fill_in("four_hundred_run_minutes", with:2)
        fill_in("four_hundred_run_seconds", with:50)
        fill_in("pushup_reps", with:20)
        fill_in("pullup_reps", with:3)
        fill_in("hang_minutes", with:0)
        fill_in("hang_seconds", with:19)
        choose(id="units_imperial")
        fill_in("body_weight", with:195)
        select("Back Squat", from: "squat")
        fill_in("squat_weight", with:136) 
        select("Trap Bar", from: "deadlift")
        fill_in("deadlift_weight", with:202)  
        select("Bench Press", from: "press")
        fill_in("press_weight", with:126)
        fill_in("pullup_weight", with:144)
        click_button("Submit Results")
        
        expect(current_path).to eq("/results")
        expect(page).to have_content("SOF Land Prep Assessment Results")
        expect(page).to have_content("Overall Score: 6")
        expect(page).to have_content("Strength Score: 18")
        expect(page).to have_content("Conditioning Score: 0")
        expect(page).to have_content("Work Capacity Score: 0")
    end 

    it 'should be a page with several options and lets you select sof maritime contract track with front squat, straigh bar dl, and oh press' do
        select("SOF Maritime Contract", from: "track")  
        click_button("Select Track")
        
        expect(page).to have_content("SOF Maritime Contract Assessments")

        fill_in("ruck_hours", with:4)
        fill_in("ruck_minutes", with:15)
        fill_in("five_mile_minutes", with:59)
        fill_in("five_mile_seconds", with:15)
        fill_in("two_thousand_swim_minutes", with:59)
        fill_in("two_thousand_swim_seconds", with:15)
        fill_in("one_and_half_mile_run_minutes", with:20)
        fill_in("one_and_half_mile_run_seconds", with:50)
        fill_in("five_hundred_swim_minutes", with:20)
        fill_in("five_hundred_swim_seconds", with:50)
        fill_in("four_hundred_run_minutes", with:2)
        fill_in("four_hundred_run_seconds", with:30)
        fill_in("pushup_reps", with:20)
        fill_in("pullup_reps", with:2)
        fill_in("hang_minutes", with:0)
        fill_in("hang_seconds", with:19)
        choose(id="units_imperial")
        fill_in("body_weight", with:195)
        select("Front Squat", from: "squat")
        fill_in("squat_weight", with:187) 
        select("Straight Bar", from: "deadlift")
        fill_in("deadlift_weight", with:202)  
        select("Overhead Press (1 Arm)", from: "press")
        fill_in("press_weight", with:36)
        fill_in("pullup_weight", with:136)
        click_button("Submit Results")
        
        expect(current_path).to eq("/results")
        expect(page).to have_content("SOF Maritime Contract Assessment Results")
        expect(page).to have_content("Overall Score: 7")
        expect(page).to have_content("Strength Score: 12")
        expect(page).to have_content("Conditioning Score: 9")
        expect(page).to have_content("Work Capacity Score: 0")
    end 

    it 'should be a page with several options and lets you select a track' do
        select("SOF Land Contract", from: "track")  
        click_button("Select Track")
        
        expect(page).to have_content("SOF Land Contract Assessments")

        fill_in("ruck_hours", with:3)
        fill_in("ruck_minutes", with:15)
        fill_in("five_mile_minutes", with:55)
        fill_in("five_mile_seconds", with:15)
        fill_in("one_and_half_mile_run_minutes", with:20)
        fill_in("one_and_half_mile_run_seconds", with:50)
        fill_in("four_hundred_run_minutes", with:2)
        fill_in("four_hundred_run_seconds", with:30)
        fill_in("pushup_reps", with:40)
        fill_in("pullup_reps", with:8)
        fill_in("hang_minutes", with:0)
        fill_in("hang_seconds", with:19)
        choose(id="units_imperial")
        fill_in("body_weight", with:195)
        select("Back Squat", from: "squat")
        fill_in("squat_weight", with:222) 
        select("Trap Bar", from: "deadlift")
        fill_in("deadlift_weight", with:222)  
        select("Bench Press", from: "press")
        fill_in("press_weight", with:201)
        fill_in("pullup_weight", with:201)
        click_button("Submit Results") 

        expect(current_path).to eq("/results")
        expect(page).to have_content("SOF Land Contract Assessment Results")
        expect(page).to have_content("Overall Score: 19")
        expect(page).to have_content("Strength Score: 39")
        expect(page).to have_content("Conditioning Score: 17")
        expect(page).to have_content("Work Capacity Score: 2")
    end 

    it 'operator short track tests' do
        select("Operator - Short", from: "track")  
        click_button("Select Track")
        
        expect(page).to have_content("Operator(short) Assessments")

        select("5 Mile Run", from: "operator_run_or_ruck")
        fill_in("operator_ruck_or_run_hours", with:0)
        fill_in("operator_ruck_or_run_minutes", with:36)
        fill_in("one_and_half_mile_run_minutes", with:12)
        fill_in("one_and_half_mile_run_seconds", with:03)
        fill_in("four_hundred_run_minutes", with:1)
        fill_in("four_hundred_run_seconds", with:30)
        fill_in("pushup_reps", with:50)
        fill_in("pullup_reps", with:9)
        fill_in("hang_minutes", with:1)
        fill_in("hang_seconds", with:19)
        choose(id="units_imperial")
        fill_in("body_weight", with:195)
        fill_in("tgu_weight", with:60)
        select("Back Squat", from: "squat")
        fill_in("squat_weight", with:292) 
        select("Trap Bar", from: "deadlift")
        fill_in("deadlift_weight", with:362)  
        select("Bench Press", from: "press")
        fill_in("press_weight", with:241)
        fill_in("pullup_weight", with:261)
        click_button("Submit Results") 

        expect(current_path).to eq("/results")
        expect(page).to have_content("Operator(short) Assessment Results")
        expect(page).to have_content("Overall Score: 80")
        expect(page).to have_content("Strength Score: 86")
        expect(page).to have_content("Conditioning Score: 67")
        expect(page).to have_content("Work Capacity Score: 87")
    end 

    it 'has operator long track tests' do
        select("Operator - Long", from: "track")  
        click_button("Select Track")
        
        expect(page).to have_content("Operator(long) Assessments")

        fill_in("ruck_hours", with:1)
        fill_in("ruck_minutes", with:55)
        fill_in("five_mile_minutes", with:42)
        fill_in("five_mile_seconds", with:15)
        fill_in("one_and_half_mile_run_minutes", with:12)
        fill_in("one_and_half_mile_run_seconds", with:03)
        fill_in("four_hundred_run_minutes", with:1)
        fill_in("four_hundred_run_seconds", with:30)
        fill_in("pushup_reps", with:50)
        fill_in("pullup_reps", with:9)
        fill_in("hang_minutes", with:1)
        fill_in("hang_seconds", with:19)
        choose(id="units_imperial")
        fill_in("body_weight", with:195)
        fill_in("tgu_weight", with:60)
        select("Back Squat", from: "squat")
        fill_in("squat_weight", with:292) 
        select("Trap Bar", from: "deadlift")
        fill_in("deadlift_weight", with:362)  
        select("Bench Press", from: "press")
        fill_in("press_weight", with:241)
        fill_in("pullup_weight", with:261)
        click_button("Submit Results") 
        
        expect(current_path).to eq("/results")
        expect(page).to have_content("Operator(long) Assessment Results")
        expect(page).to have_content("Overall Score: 82")
        expect(page).to have_content("Strength Score: 86")
        expect(page).to have_content("Conditioning Score: 73")
        expect(page).to have_content("Work Capacity Score: 87")
    end 

    it 'has HRT track tests' do
        select("HRT", from: "track")  
        click_button("Select Track")
        
        expect(page).to have_content("HRT Assessments")

        fill_in("ruck_hours", with:1)
        fill_in("ruck_minutes", with:55)
        fill_in("five_mile_minutes", with:42)
        fill_in("five_mile_seconds", with:15)
        fill_in("two_mile_run_minutes", with:14)
        fill_in("two_mile_run_seconds", with:03)
        fill_in("four_hundred_run_minutes", with:1)
        fill_in("four_hundred_run_seconds", with:30)
        fill_in("pushup_reps", with:50)
        fill_in("pullup_reps", with:9)
        fill_in("hang_minutes", with:1)
        fill_in("hang_seconds", with:19)
        choose(id="units_imperial")
        fill_in("body_weight", with:195)
        fill_in("dip_reps", with:20)
        select("Back Squat", from: "squat")
        fill_in("squat_weight", with:292) 
        select("Trap Bar", from: "deadlift")
        fill_in("deadlift_weight", with:362)  
        select("Bench Press", from: "press")
        fill_in("press_weight", with:241)
        fill_in("pullup_weight", with:261)
        click_button("Submit Results") 
        
        expect(current_path).to eq("/results")
        expect(page).to have_content("HRT Assessment Results")
        expect(page).to have_content("Overall Score: 89")
        expect(page).to have_content("Strength Score: 86")
        expect(page).to have_content("Conditioning Score: 86")
        expect(page).to have_content("Work Capacity Score: 94")
    end 

    it 'has LEO track tests' do
        select("LEO", from: "track")  
        click_button("Select Track")
        
        expect(page).to have_content("LEO Assessments")

        select("3 Mile Run", from: "prep_run_or_ruck")
        fill_in("ruck_or_run_hours", with:0)
        fill_in("ruck_or_run_minutes", with:30)
        fill_in("one_and_half_mile_run_minutes", with:12)
        fill_in("one_and_half_mile_run_seconds", with:50)
        fill_in("four_hundred_run_minutes", with:1)
        fill_in("four_hundred_run_seconds", with:30)
        fill_in("pushup_reps", with:50)
        fill_in("pullup_reps", with:9)
        fill_in("hang_minutes", with:1)
        fill_in("hang_seconds", with:19)
        choose(id="units_imperial")
        fill_in("body_weight", with:195)
        select("Back Squat", from: "squat")
        fill_in("squat_weight", with:266) 
        select("Trap Bar", from: "deadlift")
        fill_in("deadlift_weight", with:303)  
        select("Bench Press", from: "press")
        fill_in("press_weight", with:194)
        fill_in("pullup_weight", with:215)
        click_button("Submit Results")
        
        expect(current_path).to eq("/results")
        expect(page).to have_content("LEO Assessment Results")
        expect(page).to have_content("Overall Score: 85")
        expect(page).to have_content("Strength Score: 96")
        expect(page).to have_content("Conditioning Score: 66")
        expect(page).to have_content("Work Capacity Score: 92")
    end 

    it 'has fir urban track tests' do
        select("Fire Urban", from: "track")  
        click_button("Select Track")
        
        expect(page).to have_content("Fire - Urban Assessments")

        select("4 Mile Ruck", from: "prep_run_or_ruck")
        fill_in("ruck_or_run_hours", with:1)
        fill_in("ruck_or_run_minutes", with:8)
        fill_in("one_and_half_mile_run_minutes", with:12)
        fill_in("one_and_half_mile_run_seconds", with:50)
        fill_in("four_hundred_run_minutes", with:1)
        fill_in("four_hundred_run_seconds", with:30)
        fill_in("pushup_reps", with:50)
        fill_in("pullup_reps", with:9)
        fill_in("hang_minutes", with:1)
        fill_in("hang_seconds", with:19)
        choose(id="units_imperial")
        fill_in("body_weight", with:195)
        select("Front Squat", from: "squat")
        fill_in("squat_weight", with:166) 
        select("Straight Bar", from: "deadlift")
        fill_in("deadlift_weight", with:203)  
        select("Bench Press", from: "press")
        fill_in("press_weight", with:194)
        fill_in("pullup_weight", with:215)
        click_button("Submit Results")
        
        expect(current_path).to eq("/results")
        expect(page).to have_content("Fire - Urban Assessment Results")
        expect(page).to have_content("Overall Score: 81")
        expect(page).to have_content("Strength Score: 80")
        expect(page).to have_content("Conditioning Score: 72")
        expect(page).to have_content("Work Capacity Score: 92")
    end 
end 